# Generated by Django 4.2.15 on 2024-09-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='destinatario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='remitente',
            field=models.CharField(max_length=100),
        ),
    ]
